# Generated by Django 5.1.7 on 2025-03-06 18:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0002_application'),
    ]

    operations = [
        migrations.AddField(
            model_name='job',
            name='contact',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
    ]
