# Generated by Django 5.1.7 on 2025-03-09 14:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0004_remove_job_category_job_expire_date_job_status_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='job',
            name='expire_date',
        ),
        migrations.RemoveField(
            model_name='job',
            name='status',
        ),
    ]
