# Generated by Django 5.1.7 on 2025-03-10 02:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0006_job_category_alter_application_job_alter_job_contact_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='job',
            name='slug',
            field=models.SlugField(blank=True, unique=True),
        ),
    ]
