# Generated by Django 5.1.7 on 2025-03-10 03:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0008_application_staus'),
    ]

    operations = [
        migrations.RenameField(
            model_name='application',
            old_name='staus',
            new_name='status',
        ),
    ]
